### ISSUE TITLE
Occupancy sensors

### ISSUE THREAD

**Issue by bluewalk** [minamoanes/homebridge-homekit-control#21]
Hi I don't seem to find information if your plugin supports occupancy sensors (which are basically motion sensors anyway).

Soon I will receive my Aqara FP2 which publishes occupancy sensors and I need to have those routed to MQTT somehow, I found your plugin which seems promising to connect it to homebridge (and then somehow report sensor states to MQTT, which most likely requires adding MQTT support to this plugin as well), but in order for that it needs to support motion sensors :)

Any info on this?

**Comment by vmummer** [comment]
Have you tried it?


Because my eccobee has them and I can see it.
